require './tester'
tester = Tester.new

exp_x =  " GATCGGCAT "
exp_y = "CAATGTGAATC"
exp_cost = "*-++--+-++* (-3)"
x = "GATCGGCAT"
y = "CAATGTGAATC"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "handout example"

exp_x =  " GATCGGCAT "
exp_y = "CAATGTGAATC"
exp_cost = "*-++--+-++* (-3)"
x = "GATCGGCAT"
y = "CAATGTGAATC"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "handout"

exp_x = "GC C"
exp_y = "TCGC"
exp_cost = "-+*+ (-1)"
x = "GCC"
y = "TCGC"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "personal test"

x = "GCGCGCGCGC"
y = "ATATATATTATATT"
exp_cost = -18
tester.add_general_test x, y, exp_cost, "completely different genes"

x = "GCGCGCGCGC"
y = "GCGCGCGCGC"
exp_cost = 10
tester.add_general_test x, y, exp_cost, "completely same genes"

x = "GATTACATACA"
y = "ACATACATTAG"
exp_cost = 11
tester.add_general_test x, y, exp_cost, "completely same reversed genes"

exp_x = "           "
exp_y = "CAATGTGAATC"
exp_cost = "*********** (-22)"
x = ""
y = "CAATGTGAATC"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "empty gene"

exp_x = "TTTTTTTTCC"
exp_y = "TTTTTTTTGG"
exp_cost = "++++++++-- (6)"
x = "CCTTTTTTTT"
y = "TTTTTTTTGG"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "reverse test"

exp_x = "TTTTTTTTTTTTTTTTTTTT"
exp_y = "TTTTTTTTTTTTTTTTTTTT"
exp_cost = "++++++++++++++++++++ (20)"
x = "TTTTTTTTTTTTTTTTTTTT"
y = "TTTTTTTTTTTTTTTTTTTT"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "20 test"

exp_x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_cost = "++++++++++++++++++++++++++++++++++++++++ (40)"
x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "40 test"

exp_x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_cost = "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ (60)"
x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "60 test"

exp_x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_cost = "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ (80)"
x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "80 test"

exp_x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_y = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
exp_cost = "---------------------------------------------------------------------------------------------------- (-100)"
x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
y = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "100 test"


exp_x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_y = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
exp_cost = "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- (-1000)"
x = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
y = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "1000 test"

exp_x = "         T"
exp_y = "TTTTTTTTTT"
exp_cost = "*********+ (-17)"
x = "T"
y = "TTTTTTTTTT"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "10x1 test"

exp_x = "                   T"
exp_y = "TTTTTTTTTTTTTTTTTTTT"
exp_cost = "*******************+ (-37)"
x = "T"
y = "TTTTTTTTTTTTTTTTTTTT"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "20x1 test"

exp_x = "                                       T"
exp_y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_cost = "***************************************+ (-77)"
x = "T"
y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "40x1 test"

exp_x = "                                                           T"
exp_y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_cost = "***********************************************************+ (-117)"
x = "T"
y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "60x1 test"

exp_x = "                                                                               T"
exp_y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
exp_cost = "*******************************************************************************+ (-157)"
x = "T"
y = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "80x1 test"

exp_x = "                                                                                                   T"
exp_y = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
exp_cost = "***************************************************************************************************- (-199)"
x = "T"
y = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "100x1 test"

exp_x = "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       T"
exp_y = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
exp_cost = "***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************- (-1999)"
x = "T"
y = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "1000x1 test"

x = "TACCAGAC"
y = "GATACTGACT"
tester.add_perform_test x, y, "10 avg test"

x = "TACCAGATACGTCAAGAC"
y = "GATACTGATTGACACTGACT"
tester.add_perform_test x, y, "20 avg test"

x = "TACCAGATTACCGGACTAACCAGATACGTCAAGAC"
y = "GATACTGAGTCCCATTGACACGTATACATTGACACTGACT"
tester.add_perform_test x, y, "40 avg test"

x = "TACCAGATCTGACATTGACACAGATACCGGACTCGTCAAACCAGATACGTCAAGAC"
y = "GATACTGAGTCGATCATTGACACTGATTGCCATTGACCGGACTATACATTGACACTGACT"
tester.add_perform_test x, y, "60 avg test"

x = "TACCAGATTACCGGACTAACCGTCACCTGGGAGTCCACCAGATTACCGGACTAACCAGATACGTCAAGAC"
y = "GATACTGAGTCCCATTGACACGTTCAGTCCACTGGCAGACTGATACTGAGTCCCATTGACACGTATCATTGACACTGACT"
tester.add_perform_test x, y, "80 avg test"

x = "TACCAGATTACCGGACTAACCGTCACCTGGTGACTAACGCACGTTAGCGAGTCCACCAGATTACCGGACTAACCAGATACGTCAAGAC"
y = "GATACTGAGTCCCATTGACTGGGAGTCACGTTCAGTGATACTGAACTCCACTGGCAGACTGATACTGAGTCCCATTGAACACGTATCATTGACACTGACT"
tester.add_perform_test x, y, "100 avg test"


x = "TACCAGATTACCGGACTAACCGTCACCTGGTGACTAACGCATCAGTACTCCACCAGATTACCAGATTACCGGACTAACCGTCACCTGGTGACTAATACCAGATTACCGGACTAACCGTCACCTGGGCTAACGCACGTTACGGTCACCAGTTCCGGACAACCAGATACGTAAGACCGCACGTTAGCGAGTCCACCAGATTACCGGACTAACCAGATTACCAGATTACCGGACTAACCGTCACCTGGTGACTAACGCACGTTAGCGAGTCCACCAGATTACCGGACTAACCAGATACGTCAAGACACGTCAAGACTACCGGACTAACCAGATACTACCAGATTACCGGACTAACCGTCACCTGGTGACTAACGCACGTTAGCGAGTCCACCAGATTACCGGACTAACCAGATACGTCAAGACGTCAAGACTGATACTGAACTCCACTGGCGTTACCATACCAGATTACCGGACTAACCGTCACCTGGTGACTAACGCACGTTAGCGAGTCCACCAGATTACCGGACTAACCAGATACGTCAAGACTACCAGATTACCGGACTAACCGTCACCTGGTGACTAACGCACGTTAGCGAGTCCACCAGATTACCGGACTAACCAGATACGTCAAGACGATTACCGGACTAACCGTCACCTGGTGACTAACGCACGTTAGCGAGTCCACCAGATTACCGGACTAACCAGATACGTCAAGACTACCAGATTACCGGACTAACCGTCACCTGGTGACTAACGCACGTTAGCGAGTCCACCAGATTACCGGACTAACCAGATACGTCAAGACTAGCGAGTCCACCAGATTACCGGACTAACCAGATACGTCAAACCGTCACCTGGTGACTAACGCACGTTAGCGAGTCCACCAAGACTACTGAACTCCACTGGCAGACTGCACGTTCAGTCCACTGGCAGACTGATACTGAGTCCCATCACTGGGAGTCACGTTCAGTGATACTGAACTCCACTGGCAGACTG"
y = "GATACTGAGTCCCATTGACTGGGAGTCACGTTCAGTGTAACACGTATCATTGACACTACTGATCCCATTGAACAGTAGACTGATACTGAGTTACCGGACTAATCCCATTGAGTCCACCAGATTACGGACACTGGGAGTCACGTTCAGTGATACTGAACTCCACTGGCAGACTGATACTGAGTCCCATTGAACACGTATCATTGACACTGACTGATACTGAGTCCCATTGTACCGGACTAACCGTCACCTGGCCACTGGCAGACTGATACTGAGTCCCATTGAACACGTATCATTGACACTGACTGATACTGAGTCCCATTGACTGGGAGTCACGTTCAGTGATACTGAACTCCACTGGCAGACTGATACTGAGTCCCATTGAACACGTATCATTGACACTGACTGATACTGAGTCCCATTGACTGGGAGTCACGTTCAGTGATACTGAACTCCACTGGCAGACTGATACTGAGTCCCATTGAACACGTATCATTGACACTGACTGATACTGAGTCCCATTGACTGGGAGTCACGTTCAGTGATACTGAACTCCACTGGCAGACTGATACTGAGTCCCATTGAACACGTATCATTGACACTGACTGATACTGAGTCCCATTGACTGGGAGTCACGTTCAGTGATACTGAACTCCACTGGCAGACTGATACTGAGTCCCATTGAACACGTATCATTGACACTGACTGATACTGAGTCCCATTGACTGGGAGTCACGTTCAGTGATACTGAACTCCACTGGCAGACTGATACTGAGTCCCATTGAACACGTATCATTGACACTGACTGATACTGAGTCCCATTGACTGGGAGTCACGTTCAGTGATACTGAACTCCACTGGCAGACTGATACTGAGTCCCATTGAACACGTTCATTGACACTGACTGATACTGAGTCCCATTGCTGGGAGTCACGTTCAGTGATACTGAACTCCACGGCAGACTGATACTGAGTCCCATTGACACGTATCATTGACACTGACT"
tester.add_perform_test x, y, "1000 avg test"

# exp_x = "                   T"
# exp_y = "TTTTTTTTTTTTTTTTTTTT"
# exp_cost = "*******************+ (-37)"
# x = "T"
# y = "TTTTTTTTTTTTTTTTTTTT"
# tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "20x1 test"


exp_x = " CTYTG"
exp_y = "GCT TG"
exp_cost = "*++*++ (0)"
x = "CTYTG"
y = "GCTTG"
tester.add_specific_test x, y, exp_x, exp_y, exp_cost, "both spaces"

tester.run_tests
